/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import kotlin.test.Test
import kotlin.test.assertSame

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = DemoDAta(data = "Mantap cuy")
        assertSame(classUnderTest.data, "Mantap cuy")
    }
}
